/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package ss.pku.utils.jltl2ba;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 7;
  /** RegularExpression Id. */
  int ACCEPT_ALL = 9;
  /** RegularExpression Id. */
  int ACCEPT_INIT = 10;
  /** RegularExpression Id. */
  int FALSE = 11;
  /** RegularExpression Id. */
  int FI = 12;
  /** RegularExpression Id. */
  int GOTO = 13;
  /** RegularExpression Id. */
  int IF = 14;
  /** RegularExpression Id. */
  int NEVER = 15;
  /** RegularExpression Id. */
  int ZKIP = 16;
  /** RegularExpression Id. */
  int LBRACE = 17;
  /** RegularExpression Id. */
  int RBRACE = 18;
  /** RegularExpression Id. */
  int LPARENTHESIS = 19;
  /** RegularExpression Id. */
  int RPARENTHESIS = 20;
  /** RegularExpression Id. */
  int COLON = 21;
  /** RegularExpression Id. */
  int CCOLON = 22;
  /** RegularExpression Id. */
  int SEMICOLON = 23;
  /** RegularExpression Id. */
  int ONE = 24;
  /** RegularExpression Id. */
  int ARROW = 25;
  /** RegularExpression Id. */
  int BBAR = 26;
  /** RegularExpression Id. */
  int AAMPERSAND = 27;
  /** RegularExpression Id. */
  int BANG = 28;
  /** RegularExpression Id. */
  int ACCEPT_Sj = 29;
  /** RegularExpression Id. */
  int Ti_Sj = 30;
  /** RegularExpression Id. */
  int Ti_INIT = 31;
  /** RegularExpression Id. */
  int ATOM_k = 32;
  /** RegularExpression Id. */
  int INDEX = 33;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "\"accept_all\"",
    "\"accept_init\"",
    "\"false\"",
    "\"fi\"",
    "\"goto\"",
    "\"if\"",
    "\"never\"",
    "\"skip\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\"::\"",
    "\";\"",
    "\"1\"",
    "\"->\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "<ACCEPT_Sj>",
    "<Ti_Sj>",
    "<Ti_INIT>",
    "<ATOM_k>",
    "<INDEX>",
  };

}
